version: '3.8'

services:
  webapp-led:
    image: webapp-led:latest
    ports:
      - "9900:9900"
    volumes:
      - /var/rootdirs/home/fio/home/:/home/:rw
    restart: unless-stopped
  blinkled-web:
    image: blinkled-web:latest
    privileged: true
    restart: unless-stopped
    volumes:
      - /var/rootdirs/home/fio/home/:/home/:ro
    depends_on:
      - webapp-led
